# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f92ad3f828cb423255ca98d2b16ebae1c2aa38f6f7df60a56440f68c4416c5be4e0035eb6f9c00230149480f2a7ac45fb7025f1469bfe77de5878bc639f9c6b4

test:
  secret_key_base: 8f2cd0aa5d5b04aed2bf822011ccc6cf65c197cdcfd89ff8d261019a40db1368b4dde39353d626f5277a2d4f771fa1bbae0c588bf173349dbb309cf27ea76eb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
